version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

# TODO if this is required, re-enable; otherwise remove
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "weekly"
