[package]
name = "cargo-msrv-prep"
version = "0.1.0"
authors = [ "Charles Lechasseur <shiftingbeard@gmx.com>" ]
edition = "2021"
rust-version = "1.74.1"

readme = "README.md"
license = "MIT"

homepage = "https://github.com/clechasseur/msrv-prep#readme"
repository = "https://github.com/clechasseur/msrv-prep"
documentation = "https://docs.rs/cargo-msrv-prep"

description = "Cargo subcommand useful to prepare for determining/verifying a crate's MSRV"

keywords = [ "cli", "cargo", "subcommand", "testing" ]
categories = [ "command-line-utilities", "development-tools::cargo-plugins", "development-tools::testing" ]

include = [ "src/**/*", "tests/**/*", "resources/**/*", "Cargo.lock", "Cargo.toml", "LICENSE", "README.md" ]

[[bin]]
name = "cargo-msrv-unprep"
path = "src/bin/cargo_msrv_unprep.rs"

[dependencies]
cargo_metadata = "0.18.1"
clap = { version = "4.5.1", features = ["cargo", "derive"] }
clap-cargo = { version = "0.14.0", features = ["cargo_metadata"] }
clap-verbosity-flag = "2.2.0"
env_logger = "0.11.2"
log = "0.4.20"
mockall_double = "0.3.1"
thiserror = "1.0.57"
toml_edit = "0.22.6"

[dev-dependencies]
assert_cmd = "2.0.14"
assert_fs = "1.1.1"
assert_matches = "1.5.0"
indoc = "2.0.4"
mockall = "0.12.1"
predicates = "3.1.0"
test-log = "0.2.15"
toml = "0.8.10"
